from __future__ import annotations

from dataclasses import dataclass

from app.agent.steps.extract import extract_evidence
from app.agent.steps.reason import reason_and_generate
from app.agent.steps.variable import normalize_variables
from app.config import get_settings
from app.models.evidence import Evidence
from app.models.judgment import AutoResearchTrace, Judgment, ResearchAction
from app.models.question import Question
from app.models.source import Source
from app.models.topic import Topic
from app.models.variable import ResearchVariable
from app.services.content_fetcher import enrich_sources_content
from app.services.evidence_engine import (
    classify_source_origin,
    classify_tier_from_origin,
    contains_target_entity,
    is_recent_source,
    rank_sources,
)
from app.services.pdf_service import enrich_pdf_sources
from app.services.search_service import search


@dataclass(frozen=True)
class AutoResearchResult:
    sources: list[Source]
    evidence: list[Evidence]
    variables: list[ResearchVariable]
    judgment: Judgment
    actions: list[ResearchAction]
    trace: list[AutoResearchTrace]


def _priority_rank(action: ResearchAction) -> int:
    return {"high": 0, "medium": 1, "low": 2}.get(action.priority, 9)


def choose_top_actions(actions: list[ResearchAction], limit: int = 2) -> list[ResearchAction]:
    """Pick bounded补证 tasks, preferring high-priority actions."""

    actionable = [item for item in actions if item.status in {"pending", "running"}]
    high_priority = [item for item in actionable if item.priority == "high"]
    pool = high_priority or [item for item in actionable if item.priority == "medium"] or actionable
    return sorted(pool, key=lambda item: (_priority_rank(item), item.id))[:limit]


def _render_query(template: str, topic: Topic) -> str:
    entity = topic.entity or topic.topic
    return template.format(entity=entity, topic=topic.topic).strip()


def _existing_urls(sources: list[Source]) -> set[str]:
    return {item.url for item in sources if item.url}


def _is_pdf_url(url: str | None, title: str) -> bool:
    text = f"{url or ''} {title}".lower()
    return ".pdf" in text or "pdf" in text


def retrieve_from_action(
    topic: Topic,
    questions: list[Question],
    action: ResearchAction,
    existing_sources: list[Source],
    start_index: int,
    max_sources: int = 4,
    search_fn=search,
) -> tuple[list[Source], list[str]]:
    """Run real search queries generated by one structured research action."""

    question_id = action.question_id or (questions[0].id if questions else "q_auto")
    seen_urls = _existing_urls(existing_sources)
    sources: list[Source] = []
    executed_queries: list[str] = []
    source_counter = start_index
    per_query_limit = max(1, min(get_settings().retrieve_per_question_limit, 3))

    for template in action.query_templates:
        query = _render_query(template, topic)
        if not query or query in executed_queries:
            continue
        executed_queries.append(query)
        try:
            results = search_fn(query)
        except RuntimeError:
            continue
        collected_for_query = 0
        for result in results:
            url = (result.get("url") or "").strip() or None
            if url and url in seen_urls:
                continue
            if url:
                seen_urls.add(url)
            origin = classify_source_origin(
                url=url,
                title=result["title"],
                source_type=result["source_type"],
                content=result["content"],
            )
            tier = classify_tier_from_origin(origin)
            draft = Source(
                id=f"s{source_counter}",
                question_id=question_id,
                flow_type="fact" if "official" in " ".join(action.source_targets).lower() else "risk",
                search_query=query,
                url=url,
                title=result["title"],
                source_type=result["source_type"],
                provider=result.get("provider", "unknown"),
                source_origin_type=origin,
                credibility_tier={
                    "official": "tier1",
                    "professional": "tier2",
                    "content": "tier3",
                }[tier.value],
                tier=tier,
                published_at=result.get("published_at"),
                is_pdf=_is_pdf_url(url, result["title"]),
                pdf_parse_status="not_attempted" if _is_pdf_url(url, result["title"]) else "not_pdf",
                content=result["content"],
            )
            sources.append(
                draft.model_copy(
                    update={
                        "contains_entity": contains_target_entity(
                            f"{draft.title} {draft.content[:1200]}",
                            topic,
                        ),
                        "is_recent": is_recent_source(draft),
                    }
                )
            )
            source_counter += 1
            collected_for_query += 1
            if len(sources) >= max_sources or collected_for_query >= per_query_limit:
                break
        if len(sources) >= max_sources:
            break

    ranked_sources = rank_sources(enrich_pdf_sources(sources), topic, max_sources)
    enriched_sources = enrich_sources_content(ranked_sources)
    return rank_sources(enriched_sources, topic, max_sources), executed_queries


def _renumber_new_evidence(new_evidence: list[Evidence], start_index: int) -> list[Evidence]:
    return [
        item.model_copy(update={"id": f"e{index}"})
        for index, item in enumerate(new_evidence, start=start_index)
    ]


def _merge_evidence(existing: list[Evidence], new_items: list[Evidence]) -> list[Evidence]:
    seen = {(item.source_id, item.content) for item in existing}
    merged = list(existing)
    for item in new_items:
        key = (item.source_id, item.content)
        if key in seen:
            continue
        seen.add(key)
        merged.append(item)
    return merged


def _mark_action_status(
    actions: list[ResearchAction],
    selected: list[ResearchAction],
    status: str,
) -> list[ResearchAction]:
    selected_ids = {item.id for item in selected}
    return [
        item.model_copy(update={"status": status})
        if item.id in selected_ids
        else item
        for item in actions
    ]


def auto_research_loop(
    topic: Topic,
    questions: list[Question],
    sources: list[Source],
    evidence: list[Evidence],
    variables: list[ResearchVariable],
    judgment: Judgment,
    actions: list[ResearchAction],
    max_rounds: int = 1,
    action_limit: int = 2,
    retrieve_fn=retrieve_from_action,
) -> AutoResearchResult:
    """Bounded automatic补证 loop for low-confidence judgments."""

    trace: list[AutoResearchTrace] = []
    current_sources = list(sources)
    current_evidence = list(evidence)
    current_variables = list(variables)
    current_judgment = judgment
    current_actions = list(actions)

    for round_index in range(1, max_rounds + 1):
        if current_judgment.confidence != "low":
            trace.append(
                AutoResearchTrace(
                    round_index=round_index,
                    triggered=False,
                    effectiveness_status="not_triggered",
                    stop_reason=f"confidence={current_judgment.confidence}，无需自动补证",
                )
            )
            break

        selected_actions = choose_top_actions(current_actions, limit=action_limit)
        if not selected_actions:
            trace.append(
                AutoResearchTrace(
                    round_index=round_index,
                    triggered=False,
                    effectiveness_status="not_triggered",
                    stop_reason="没有可执行的结构化研究任务",
                )
            )
            break

        current_actions = _mark_action_status(current_actions, selected_actions, "running")
        round_sources: list[Source] = []
        executed_queries: list[str] = []
        for action in selected_actions:
            new_sources, queries = retrieve_fn(
                topic,
                questions,
                action,
                current_sources + round_sources,
                start_index=len(current_sources) + len(round_sources) + 1,
            )
            round_sources.extend(new_sources)
            executed_queries.extend(queries)

        if not round_sources:
            current_actions = _mark_action_status(current_actions, selected_actions, "skipped")
            trace.append(
                AutoResearchTrace(
                    round_index=round_index,
                    triggered=True,
                    selected_action_ids=[item.id for item in selected_actions],
                    executed_queries=executed_queries,
                    effectiveness_status="no_new_data",
                    stop_reason="自动补证未检索到新增可用来源",
                )
            )
            break

        extracted = extract_evidence(topic, questions, round_sources)
        renumbered = _renumber_new_evidence(extracted, len(current_evidence) + 1)
        if not renumbered:
            current_actions = _mark_action_status(current_actions, selected_actions, "skipped")
            current_sources.extend(round_sources)
            trace.append(
                AutoResearchTrace(
                    round_index=round_index,
                    triggered=True,
                    selected_action_ids=[item.id for item in selected_actions],
                    executed_queries=executed_queries,
                    new_source_ids=[item.id for item in round_sources],
                    effectiveness_status="no_new_data",
                    stop_reason="新增来源未提取出有效证据",
                )
            )
            break

        target_gap_question_ids = {
            item.question_id
            for item in selected_actions
            if item.question_id
        }
        covered_gap_question_ids = sorted(
            {
                item.question_id
                for item in renumbered
                if item.question_id and item.question_id in target_gap_question_ids
            }
        )
        is_effective = not target_gap_question_ids or bool(covered_gap_question_ids)
        current_sources.extend(round_sources)
        current_evidence = _merge_evidence(current_evidence, renumbered)
        if is_effective:
            current_variables = normalize_variables(current_evidence)
            current_judgment = reason_and_generate(topic, current_evidence, questions, current_variables)
            current_actions = current_judgment.research_actions
        else:
            current_actions = _mark_action_status(current_actions, selected_actions, "skipped")
        trace.append(
            AutoResearchTrace(
                round_index=round_index,
                triggered=True,
                selected_action_ids=[item.id for item in selected_actions],
                executed_queries=executed_queries,
                new_source_ids=[item.id for item in round_sources],
                new_evidence_ids=[item.id for item in renumbered],
                covered_gap_question_ids=covered_gap_question_ids,
                effectiveness_status="effective" if is_effective else "ineffective",
                stop_reason=(
                    f"完成本轮补证，final_confidence={current_judgment.confidence}"
                    if is_effective
                    else "新增证据未覆盖本轮目标证据缺口，保持原判断置信度"
                ),
            )
        )

        if not is_effective:
            break

        if current_judgment.confidence != "low":
            break

    return AutoResearchResult(
        sources=current_sources,
        evidence=current_evidence,
        variables=current_variables,
        judgment=current_judgment,
        actions=current_actions,
        trace=trace,
    )
